Create a variable `height` and set it to your height in meters.

In [1]:
height = 5.6

Define a tuple with the names of three different animals and print the first animal in the tuple.

In [ ]:
animals = ['lion','monkey','elephant']

Create a dictionary with keys as the names of three countries and values as their capitals. Print the capital of a specific country.

In [2]:
countries = {
    'Nepal':'Kathmandu',
    'Australia':'Canberra',
    'USA':'Washington D.C.'
}

Concatenate the strings `"Hello, "` and `"World!"` and print the result.

In [3]:
"Hello, " + "World!"

'Hello, World!'

Create a string `sentence` with the value `"Python programming is fun!"`. Replace the word `"fun"` with `"awesome"` and print the result.

In [5]:
sentence = "Python programming is fun!"
sentence = sentence.replace("fun","awesome")
sentence

'Python programming is awesome!'

Write a script that checks if a number is positive, negative, or zero and prints an appropriate message using `if-elif-else`.

In [6]:
number = 5
if number > 0:
    print('positive')
elif number < 0:
    print('negative')
else:
    print('zero')

positive


Use a nested if statement to check `if` a number is between 10 and 20 (inclusive) and whether it is even or odd.

In [8]:
number = 25
if number >= 10 and number <=20:
    print('inclusive')
    if number % 2 == 0:
        print('even')
    else:
        print('odd')
else:
    print('number is not between 10 and 20')
    

number is not between 10 and 20


Use a for loop to iterate over a dictionary and print each key and value.

In [11]:
for country,capital in countries.items():
    print(f'{country} : {capital}')

Nepal : Kathmandu
Australia : Canberra
USA : Washington D.C.


Write a while loop that prints the squares of numbers from 1 to 5.

In [12]:
num = 1
while num <=5:
    print(num * num)
    num = num + 1

1
4
9
16
25


Write a function `sum_list` that takes a list of numbers as an argument and returns their sum.

In [13]:
numbers = [1,2,3,4,5]
def sum_list(nums):
    sum = 0
    for num in nums:
        sum = sum + num
    return sum

sum_list(numbers)

15

Create a function `is_prime` that takes a number as an argument and returns `True` if the number is prime and `False` otherwise.


In [17]:
def is_prime(num):
    prime = True
    for i in range(2,num//2):
        if num % i == 0:
            prime = False
            break
    return prime

is_prime(4)

True

Define a class `Student` with attributes `name` and `grade`. Include a method `display_info` that prints the student's name and grade.


In [1]:
class Student:
    def __init__(self,name,grade):
        self.name = name
        self.grade = grade

    def display_info(self):
        print(f'Name:{self.name}, grade:{self.grade}')

Create an instance of the `Student` class and update the student's grade. Call the `display_info` method to display the updated information.


In [3]:
s = Student('Ujjwal','A+')
s.display_info()

Name:Ujjwal, grade:A+


Create a set with the numbers 1, 2, 3, 4, and 5. Add the number 6 to the set and print the updated set.

In [4]:
s = {1,2,3,4,5}
s.add(6)
print(s)

{1, 2, 3, 4, 5, 6}


Create another set with the numbers 4, 5, 6, 7, and 8. Find the intersection of the two sets and print the result.

In [5]:
s2 = set((4, 5, 6, 7, 8))
s.intersection(s2)

{4, 5, 6}

Create a dictionary with keys as the names of three subjects and values as the scores. Calculate and print the average score.

In [7]:
scores = {
    'Maths':90,
    'English':89,
    'Science':80
}

sum = 0
for score in scores.values():
    sum +=score
average = sum / len(scores.items())
average

86.33333333333333

Update the score of one subject and remove another subject from the dictionary. Print the updated dictionary.

In [8]:
scores['Maths'] = 85
scores

{'Maths': 85, 'English': 89, 'Science': 80}

Import NumPy and create an array with numbers from 11 to 20.

In [9]:
import numpy as np
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Reshape this array to a 5x2 matrix and print it.

In [11]:
reshaped_arr = arr.reshape(5,2)
reshaped_arr

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

Perform element-wise multiplication with another array of the same shape.

In [12]:
reshaped_arr * reshaped_arr

array([[121, 144],
       [169, 196],
       [225, 256],
       [289, 324],
       [361, 400]])

Import Pandas and create a DataFrame from a list of dictionaries, where each dictionary represents a row of data.

In [14]:
import pandas as pd
info = [
        {'name':'ujjwal','address':'Kathmandu','salary':200000},
        {'name':'rupesh','address':'Lalitpur','salary':40000},
        {'name':'binay','address':'Kathmandu','salary':45000}
       ]
df = pd.DataFrame(info)
df

name    address  salary
0  ujjwal  Kathmandu  200000
1  rupesh   Lalitpur   40000
2   binay  Kathmandu   45000

Print the last few rows of the DataFrame.

In [15]:
df.tail()

name    address  salary
0  ujjwal  Kathmandu  200000
1  rupesh   Lalitpur   40000
2   binay  Kathmandu   45000

Select and print a specific row based on a condition (e.g., where a column value is greater than a threshold).

In [16]:
df[df['salary']<50000]

name    address  salary
1  rupesh   Lalitpur   40000
2   binay  Kathmandu   45000