In [43]:
!python -m pip install mysql-connector-python

In [7]:
import mysql.connector

In [9]:

mydb= mysql.connector.connect(
  host="localhost",
  user="root",
  password=""
 
)

In [11]:
mydb

In [83]:

mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE mydata")


In [13]:
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)
    


('information_schema',)
('mydata',)
('mydatabase',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('rosan',)
('test',)


In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('mt_everest.csv')

In [5]:
df


_id                     NAME      COUNTRY  DAY  MONTH  YEAR     ROUTE  \
0        1           TENZING NORGAY        NEPAL   29      5  1953  SOUTHCOL   
1        2           EDMUND HILLARY  NEW ZEALAND   29      5  1953  SOUTHCOL   
2        3            ERNST SCHMIED  SWITZERLAND   23      5  1956  SOUTHCOL   
3        4            JUERGE MARMET  SWITZERLAND   23      5  1956  SOUTHCOL   
4        5              ADOLF REIST  SWITZERLAND   24      5  1956  SOUTHCOL   
...    ...                      ...          ...  ...    ...   ...       ...   
5296  5297    MR. PEMBA RITA SHERPA        NEPAL   27      5  2017       NaN   
5297  5298       MR. PASANG GYALZEN        NEPAL   27      5  2017       NaN   
5298  5299  MR. MINGMA DORJI SHERPA        NEPAL   16      5  2017       NaN   
5299  5300    MR. DAWA SANGE SHERPA        NEPAL   21      5  2017       NaN   
5300  5301         MR. PASANG BHOTE        NEPAL   21      5  2017       NaN   

            NAME OF THE TEAM          LEADER  
0         BRITISH EXPEDITION  Lord John Hunt  
1         BRITISH EXPEDITION               "  
2     SWITZERLAND EXPEDITION    Alber Eggler  
3     SWITZERLAND EXPEDITION               "  
4     SWITZERLAND EXPEDITION               "  
...                      ...             ...  
5296                       "               "  
5297                     NaN             NaN  
5298                       "               "  
5299                       "               "  
5300                       "               "  

[5301 rows x 9 columns]

In [15]:
#find the number of countries which has climbed mt everest in 2017
#find the name of the person who has climbed mount everest for maximum time
df['COUNTRY'].value_counts()

COUNTRY
NEPAL       2785
USA          624
INDIA        312
UK           263
JAPAN        124
            ... 
PANAMA         1
IRISH          1
AUSTRIAN       1
ARGENTIA       1
ROMANIA        1
Name: count, Length: 101, dtype: int64

In [17]:
df_2017=df[df['YEAR']==2017]

In [23]:
df_2017['COUNTRY'].nunique()

34

In [29]:
df['NAME'].value_counts().index[0:3]

Index(['MR. LAKPA NURU SHERPA', 'MR. JANGBU SHERPA', 'MR. PASANG SHERPA'], dtype='object', name='NAME')

In [31]:
x=df['NAME'].value_counts().index[0:3]

In [39]:
df.sort_values(by='NAME',ascending=False)

_id                      NAME         COUNTRY  DAY  MONTH  YEAR  \
1026  1027               ZSOLT EROSS         HUNGARY   25      5  2002   
171    172             ZOLTAN DEMZAN  CZECHOSLOVAKIA   15     10  1984   
84      85           ZAPLOTNIK ZEREJ      YUGOSLAVIA   13      5  1978   
328    329               YVES SALINO          FRANCE    4     10  1990   
1004  1005              YVES LAMBERT     SWITZERLAND   16      5  2002   
...    ...                       ...             ...  ...    ...   ...   
1672  1673            AA RITA SHERPA           NEPAL   23      5  2006   
15      16               A.S. CHEEMA           INDIA   20      5  1963   
201    202           A KUS\TSU ETSUO           JAPAN    1      1  1985   
1202  1203          . YUICHI YOSHIDA           JAPAN   22      5  2003   
1683  1684  . JAMES A. PATTERSON III             USA   20      5  2007   

                                               ROUTE  \
1026                                 SOUTH E.\nRIDGE   
171   SOUTH POLLER\nBUT\nDESENDING\nFROM S.E.\nRIDGE   
84                                        WEST RIDGE   
328                                         SOUTHCOL   
1004                                 SOUTH E.\nRIDGE   
...                                              ...   
1672                                   NORMAL\nROUTE   
15                                          SOUTHCOL   
201                                         SOUTHCOL   
1202                                      S. E RIDGE   
1683                                       S.E.RIDGE   

                          NAME OF THE TEAM                   LEADER  
1026                                     "                        "  
171                                      "                        "  
84                     YUGOSLAV EXPEDITION              Tone Skaraj  
328                    FRENCH EVEREST EXP.  Laurence Deal\nFerriere  
1004  GENEVA EVEREST\n1952/2002 EXPEDITION         Stephene Shafter  
...                                    ...                      ...  
1672                                     "                        "  
15                       INDIAN EXPEDITION               M.S. Kohli  
201                                      "                        "  
1202                                     "                        "  
1683                                     "                        "  

[5301 rows x 9 columns]

In [49]:
df.sort_values(by='YEAR',ascending=False)

_id                  NAME      COUNTRY  DAY  MONTH  YEAR     ROUTE  \
2147  2148  MR. IGOR STOROZHENKO      UKRAINE   27      5  2088    NORMAL   
2146  2147     MR. OLEKSIY LYKOV      UKRAINE   27      5  2088    NORMAL   
2145  2146        MR. OLEG PALIY      UKRAINE   27      5  2088    NORMAL   
2144  2145   MR. SERGIEY KOVALOV      UKRAINE   27      5  2088    NORMAL   
5300  5301      MR. PASANG BHOTE        NEPAL   21      5  2017       NaN   
...    ...                   ...          ...  ...    ...   ...       ...   
4        5           ADOLF REIST  SWITZERLAND   24      5  1956  SOUTHCOL   
3        4         JUERGE MARMET  SWITZERLAND   23      5  1956  SOUTHCOL   
2        3         ERNST SCHMIED  SWITZERLAND   23      5  1956  SOUTHCOL   
1        2        EDMUND HILLARY  NEW ZEALAND   29      5  1953  SOUTHCOL   
0        1        TENZING NORGAY        NEPAL   29      5  1953  SOUTHCOL   

            NAME OF THE TEAM          LEADER  
2147                       "               "  
2146                       "               "  
2145                       "               "  
2144                       "               "  
5300                       "               "  
...                      ...             ...  
4     SWITZERLAND EXPEDITION               "  
3     SWITZERLAND EXPEDITION               "  
2     SWITZERLAND EXPEDITION    Alber Eggler  
1         BRITISH EXPEDITION               "  
0         BRITISH EXPEDITION  Lord John Hunt  

[5301 rows x 9 columns]

In [51]:
df[df['YEAR']!=2088]

_id                     NAME      COUNTRY  DAY  MONTH  YEAR     ROUTE  \
0        1           TENZING NORGAY        NEPAL   29      5  1953  SOUTHCOL   
1        2           EDMUND HILLARY  NEW ZEALAND   29      5  1953  SOUTHCOL   
2        3            ERNST SCHMIED  SWITZERLAND   23      5  1956  SOUTHCOL   
3        4            JUERGE MARMET  SWITZERLAND   23      5  1956  SOUTHCOL   
4        5              ADOLF REIST  SWITZERLAND   24      5  1956  SOUTHCOL   
...    ...                      ...          ...  ...    ...   ...       ...   
5296  5297    MR. PEMBA RITA SHERPA        NEPAL   27      5  2017       NaN   
5297  5298       MR. PASANG GYALZEN        NEPAL   27      5  2017       NaN   
5298  5299  MR. MINGMA DORJI SHERPA        NEPAL   16      5  2017       NaN   
5299  5300    MR. DAWA SANGE SHERPA        NEPAL   21      5  2017       NaN   
5300  5301         MR. PASANG BHOTE        NEPAL   21      5  2017       NaN   

            NAME OF THE TEAM          LEADER  
0         BRITISH EXPEDITION  Lord John Hunt  
1         BRITISH EXPEDITION               "  
2     SWITZERLAND EXPEDITION    Alber Eggler  
3     SWITZERLAND EXPEDITION               "  
4     SWITZERLAND EXPEDITION               "  
...                      ...             ...  
5296                       "               "  
5297                     NaN             NaN  
5298                       "               "  
5299                       "               "  
5300                       "               "  

[5297 rows x 9 columns]

In [55]:
df.columns

Index(['_id', 'NAME', 'COUNTRY', 'DAY', 'MONTH', 'YEAR', 'ROUTE',
       'NAME OF THE TEAM', 'LEADER'],
      dtype='object')

In [59]:
 df=pd.read_csv('mt_everest.csv',usecols=['NAME','COUNTRY'])

In [61]:
df

NAME      COUNTRY
0              TENZING NORGAY        NEPAL
1              EDMUND HILLARY  NEW ZEALAND
2               ERNST SCHMIED  SWITZERLAND
3               JUERGE MARMET  SWITZERLAND
4                 ADOLF REIST  SWITZERLAND
...                       ...          ...
5296    MR. PEMBA RITA SHERPA        NEPAL
5297       MR. PASANG GYALZEN        NEPAL
5298  MR. MINGMA DORJI SHERPA        NEPAL
5299    MR. DAWA SANGE SHERPA        NEPAL
5300         MR. PASANG BHOTE        NEPAL

[5301 rows x 2 columns]

In [100]:
data={
    'Name':['sunil','anil','ramesh','binay','suresh'],
    'Age':[25,30,25,28,22],
    'City':['Kathmandu','Pokhara','Kathmandu','Janakpur','Dharan'],
    'Salary':[60000,70000,80000,750000,650000]
}

In [102]:
df=pd.DataFrame(data)

In [105]:
df

Name  Age       City  Salary
0   sunil   25  Kathmandu   60000
1    anil   30    Pokhara   70000
2  ramesh   25  Kathmandu   80000
3   binay   28   Janakpur  750000
4  suresh   22     Dharan  650000

In [107]:
data2={'Name':['Ramesh','Suresh','Binay'],
       'Department':['HR','IT','Finance']}

In [109]:
df2=pd.DataFrame(data2)

In [111]:
df2

Name Department
0  Ramesh         HR
1  Suresh         IT
2   Binay    Finance

In [153]:
merged_df = pd.merge(df,df2,on='Name',how='outer')
                  

In [155]:
merged_df

Name   Age       City    Salary Department
0   Binay   NaN        NaN       NaN    Finance
1  Ramesh   NaN        NaN       NaN         HR
2  Suresh   NaN        NaN       NaN         IT
3    anil  30.0    Pokhara   70000.0        NaN
4   binay  28.0   Janakpur  750000.0        NaN
5  ramesh  25.0  Kathmandu   80000.0        NaN
6   sunil  25.0  Kathmandu   60000.0        NaN
7  suresh  22.0     Dharan  650000.0        NaN

In [117]:
df2

Name Department
0  Ramesh         HR
1  Suresh         IT
2   Binay    Finance

In [119]:
df

Name  Age       City  Salary
0   sunil   25  Kathmandu   60000
1    anil   30    Pokhara   70000
2  ramesh   25  Kathmandu   80000
3   binay   28   Janakpur  750000
4  suresh   22     Dharan  650000

In [157]:
df

Name  Age       City  Salary
0   sunil   25  Kathmandu   60000
1    anil   30    Pokhara   70000
2  ramesh   25  Kathmandu   80000
3   binay   28   Janakpur  750000
4  suresh   22     Dharan  650000

In [159]:
df=pd.read_csv('mt_everest.csv')

In [165]:
df.isnull()['LEADER'].unique()

array([False,  True])

In [169]:
df.isnull().sum()#to check the null value

_id                    0
NAME                   0
COUNTRY                0
DAY                    0
MONTH                  0
YEAR                   0
ROUTE               2609
NAME OF THE TEAM      93
LEADER               129
dtype: int64

In [171]:
df_no_missing=df.dropna()

In [175]:
df_no_missing.isnull().sum()

_id                 0
NAME                0
COUNTRY             0
DAY                 0
MONTH               0
YEAR                0
ROUTE               0
NAME OF THE TEAM    0
LEADER              0
dtype: int64

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5301 entries, 0 to 5300
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   _id               5301 non-null   int64 
 1   NAME              5301 non-null   object
 2   COUNTRY           5301 non-null   object
 3   DAY               5301 non-null   int64 
 4   MONTH             5301 non-null   int64 
 5   YEAR              5301 non-null   int64 
 6   ROUTE             2692 non-null   object
 7   NAME OF THE TEAM  5208 non-null   object
 8   LEADER            5172 non-null   object
dtypes: int64(4), object(5)
memory usage: 372.9+ KB


In [179]:
df_no_missing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2615 entries, 0 to 2691
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   _id               2615 non-null   int64 
 1   NAME              2615 non-null   object
 2   COUNTRY           2615 non-null   object
 3   DAY               2615 non-null   int64 
 4   MONTH             2615 non-null   int64 
 5   YEAR              2615 non-null   int64 
 6   ROUTE             2615 non-null   object
 7   NAME OF THE TEAM  2615 non-null   object
 8   LEADER            2615 non-null   object
dtypes: int64(4), object(5)
memory usage: 204.3+ KB


In [181]:
# from sqlalchemy import create_engine

# # 'postgresql://username:password@localhost:5432/database_name'
# # Creating a SQLite database engine
# engine = create_engine('sqlite:///your_database.db')

# # Reading data from a SQL table into a DataFrame
# df_sql = pd.read_sql_table('your_table', con=engine)

# # Display the first few rows of the DataFrame
# print(df_sql.head())

# Create database
# create a table
# read table to make dataframe

In [183]:
axis=1
clean-df=original_df.dropna()
fillna#fill the null values
inplace=true #change the original dataframe
ffill=forward fill
interpolate
fillna='unknown '


SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (4018445769.py, line 2)

In [185]:
data={'A':[1,2,None,4],
      'B':[5,None,7,8],
      'C':[9,10,5,6]}

In [187]:
df=pd.DataFrame(data)

In [189]:
df

A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  7.0   5
3  4.0  8.0   6

In [191]:
cleaned_df_row=df.dropna()#removes all the  row that includes the null values

In [195]:
cleaned_df_row

A    B  C
0  1.0  5.0  9
3  4.0  8.0  6

In [197]:
cleaned_df_column=df.dropna(axis=1)

In [199]:
cleaned_df_column



C
0   9
1  10
2   5
3   6

In [201]:
import numpy as np

In [203]:
data=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [207]:
min_val=np.min(data,axis=0)
max_val=np.max(data,axis=0)
scaled_data=(data-min_val)/(max_val-min_val)

In [209]:
min_val

array([1, 2, 3])

In [211]:
max_val

array([7, 8, 9])

scaled_data

In [214]:
scaled_data

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [216]:
mean=np.mean(data,axis=0)
std_dev=np.std(data,axis=0)
standardized_data=(data-mean)/std_dev

In [218]:
standardized_data

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [224]:
standardized_data.mean()

2.4671622769447922e-17

In [226]:
standardized_data.std()

1.0

In [230]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [231]:
scaler=MinMaxScaler()

In [234]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [236]:
scaled_data=scaler.fit_transform(data)

In [238]:
scaled_data

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [240]:
sacaler=StandardScaler()

In [244]:
standardized_data=scaler.fit_transform(data)

In [246]:
standardized_data



array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [256]:
from sklearn.datasets import load_iris

In [260]:
from sklearn.feature_selection import  SelectKBest

In [262]:
from sklearn.feature_selection import chi2

In [264]:
from sklearn.model_selection import train_test_split

In [266]:
iris=load_iris()

In [280]:
X,y=iris.data,iris.target

In [308]:
k = 2


In [300]:
selector = SelectKBest(score_func=chi2, k=k)

In [302]:
X_train_selected = selector.fit_transform(X_train, y_train)

In [304]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [312]:
selected_features = [iris.feature_names[i] for i in selector.get_support(indices=True)]

In [314]:

print(selected_features)

['petal length (cm)', 'petal width (cm)']


In [318]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [320]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [322]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [326]:
from sklearn.datasets import fetch_california_housing

In [328]:
from sklearn.feature_selection import f_regression

In [332]:
from sklearn.feature_selection import SelectKBest

In [334]:
from sklearn.model_selection import train_test_split

In [338]:
california_housing=fetch_california_housing()

In [340]:
x,y=california_housing.data, california_housing.target

In [346]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2,random_state=42)


In [348]:
k=2

In [352]:
selector=SelectKBest(score_func=f_regression,k=k)

In [354]:
x_train_selected=selector.fit_transform(x_train,y_train)

In [356]:

print('Selected features based on ANOVA F-test:')
selected_feature_indices=selector.get_support(indices=True)
selected_feature_names=[california_housing.feature_names[i] for i in selected_feature_indices]
print(selected_feature_names)

Selected features based on ANOVA F-test:
['MedInc', 'AveRooms']


In [390]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Select features using a RandomForestClassifier
selector = SelectFromModel(RandomForestClassifier(n_estimators=100))
selected_features = selector.fit_transform(X_train, y_train)

# Print selected features
print("Selected features based on RandomForestClassifier:")
print(selected_features.shape[1])  # Number of selected features

selected_features = [iris.feature_names[i] for i in selector.get_support(indices=True)]

print(selected_features)

Selected features based on RandomForestClassifier:
2
['petal length (cm)', 'petal width (cm)']


In [400]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Select features using a RandomForestClassifier
selector = SelectFromModel(RandomForestClassifier(n_estimators=100))
selected_features = selector.fit_transform(X_train, y_train)

# Print selected features
print("Selected features based on RandomForestClassifier:")
print(selected_features.shape[1])  # Number of selected features

selected_features = [iris.feature_names[i] for i in selector.get_support(indices=True)]

print(selected_features)


from sklearn.datasets import fetch_california_housing
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# Load the California housing dataset
california_housing = fetch_california_housing()
X, y = california_housing.data, california_housing.target

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Select features using a RandomForestRegressor
selector = SelectFromModel(RandomForestRegressor(n_estimators=100))
selected_features = selector.fit_transform(X_train, y_train)

# Print selected features
print("Selected features based on RandomForestRegressor:")
print(selected_features.shape[1])  # Number of selected features

selected_feature_indices = selector.get_support(indices=True)
selected_feature_names = [california_housing.feature_names[i] for i in selected_feature_indices]
print(selected_feature_names)

Selected features based on RandomForestClassifier:
2
['petal length (cm)', 'petal width (cm)']
Selected features based on RandomForestRegressor:
2
['MedInc', 'AveOccup']


In [402]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

column_names = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation",
                "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
df = pd.read_csv('income_data.csv', header=None, names=column_names, na_values=" ?")

# Selecting only categorical features for demonstration
categorical_features = df[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']]

# One-hot encode categorical features
encoder = OneHotEncoder()
encoded_features = encoder.fit_transform(categorical_features)

# Convert to dense array for easier inspection
encoded_features_dense = encoded_features.toarray()

# Print original and encoded features
print("Original Features Shape:", categorical_features.shape)
print("Original Categorical Features (First 5 samples):")
print(categorical_features.head())
print("\nEncoded Features Shape:", encoded_features_dense.shape)
print("Encoded Features (First 5 samples):")
print(encoded_features_dense[:5])

Original Features Shape: (32561, 8)
Original Categorical Features (First 5 samples):
           workclass   education       marital-status          occupation  \
0          State-gov   Bachelors        Never-married        Adm-clerical   
1   Self-emp-not-inc   Bachelors   Married-civ-spouse     Exec-managerial   
2            Private     HS-grad             Divorced   Handlers-cleaners   
3            Private        11th   Married-civ-spouse   Handlers-cleaners   
4            Private   Bachelors   Married-civ-spouse      Prof-specialty   

     relationship    race      sex  native-country  
0   Not-in-family   White     Male   United-States  
1         Husband   White     Male   United-States  
2   Not-in-family   White     Male   United-States  
3         Husband   Black     Male   United-States  
4            Wife   Black   Female            Cuba  

Encoded Features Shape: (32561, 102)
Encoded Features (First 5 samples):
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0

In [404]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

column_names = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation",
                "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
df = pd.read_csv('income_data.csv', header=None, names=column_names, na_values=" ?")

# Selecting only categorical features for demonstration
categorical_features = df[['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']]

# One-hot encode categorical features
encoder = OneHotEncoder()
encoded_features = encoder.fit_transform(categorical_features)

# Convert to dense array for easier inspection
encoded_features_dense = encoded_features.toarray()

# Print original and encoded features
print("Original Features Shape:", categorical_features.shape)
print("Original Categorical Features (First 5 samples):")
print(categorical_features.head())
print("\nEncoded Features Shape:", encoded_features_dense.shape)
print("Encoded Features (First 5 samples):")
print(encoded_features_dense[:5])

Original Features Shape: (32561, 8)
Original Categorical Features (First 5 samples):
           workclass   education       marital-status          occupation  \
0          State-gov   Bachelors        Never-married        Adm-clerical   
1   Self-emp-not-inc   Bachelors   Married-civ-spouse     Exec-managerial   
2            Private     HS-grad             Divorced   Handlers-cleaners   
3            Private        11th   Married-civ-spouse   Handlers-cleaners   
4            Private   Bachelors   Married-civ-spouse      Prof-specialty   

     relationship    race      sex  native-country  
0   Not-in-family   White     Male   United-States  
1         Husband   White     Male   United-States  
2   Not-in-family   White     Male   United-States  
3         Husband   Black     Male   United-States  
4            Wife   Black   Female            Cuba  

Encoded Features Shape: (32561, 102)
Encoded Features (First 5 samples):
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0

In [406]:
from sklearn.preprocessing import LabelEncoder

# Sample labels
labels = ['cat', 'dog', 'bird', 'cat', 'dog', 'bird']

# Initialize LabelEncoder
encoder = LabelEncoder()

# Encode labels
encoded_labels = encoder.fit_transform(labels)

# Print original and encoded labels
print("Original Labels:", labels)
print("Encoded Labels:", encoded_labels)

Original Labels: ['cat', 'dog', 'bird', 'cat', 'dog', 'bird']
Encoded Labels: [1 2 0 1 2 0]
