In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# Define the employee data
employee_data = np.array([
    [28, 50000, 4],
    [32, 60000, 7],
    [25, 45000, 2],
    [30, 55000, 5],
    [35, 70000, 9],
    [27, 48000, 3],
    [29, 52000, 6],
    [31, 58000, 8],
    [26, 46000, 1],
    [33, 65000, 10],
    [22, 38000, 3],   # Age 22, salary 38000, experience 3 years
    [24, 42000, 1],   # Age 24, salary 42000, experience 1 year
    [23, 40000, 2],   # Age 23, salary 40000, experience 2 years
    [36, 72000, 11],  # Age 36, salary 72000, experience 11 years
    [34, 67000, 9],   # Age 34, salary 67000, experience 9 years
    [21, 36000, 2],   # Age 21, salary 36000, experience 2 years
    [20, 34000, 1],   # Age 20, salary 34000, experience 1 year
    [25, 46000, 4],   # Age 25, salary 46000, experience 4 years
    [31, 60000, 8],   # Age 31, salary 60000, experience 8 years
    [29, 52000, 6] 
])

# Define feature names
feature_names = ['age', 'salary', 'experience']

# Create labels
labels = np.array([8, 7, 6, 9, 8, 6, 7, 8, 5, 9,
                   7, 6, 5, 8, 7, 5, 4, 6, 8, 7])  # Assuming 'performance' as the target variable

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(employee_data, labels, test_size=0.2, random_state=42)

# Initialize StandardScaler
scaler = StandardScaler()

# Fit and transform the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test data (using the same scaler fitted on training data)
X_test_scaled = scaler.transform(X_test)

# Initialize RandomForestRegressor for predicting continuous "experience"
regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Fit the regressor to the training data
regressor.fit(X_train_scaled, y_train)

# Predict "experience" on the test data
y_pred = regressor.predict(X_test_scaled)

# Evaluate the model using Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Print feature importances based on RandomForestRegressor
print("Feature Importances:")
for feature, importance in zip(feature_names, regressor.feature_importances_):
    print(f"{feature}: {importance}")

# Example prediction for a new data point (if needed)
new_data_point = np.array([[26, 46000, 1]])  # Example new data point (age, salary, performance)
predicted_performance = regressor.predict(scaler.transform(new_data_point))
print(f"Predicted Performance: {predicted_performance}")

Mean Squared Error: 0.8157500000000001
Feature Importances:
age: 0.2989452754736683
salary: 0.27644548498897675
experience: 0.42460923953735497
Predicted Performance: [5.35]


In [3]:
import numpy as np

In [11]:
arr= np.array([[[1,2,3,4],[5,6,7,8]]])


In [15]:
arr.shape

(1, 2, 4)

In [23]:
arr=np.arange(15)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
d=arr.reshape(1,3,5)

In [33]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [35]:
d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [39]:
d.shape

(1, 3, 5)

In [43]:
d[2:1]

array([], shape=(0, 3, 5), dtype=int32)

In [45]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [47]:
d[2:1]

array([], shape=(0, 3, 5), dtype=int32)

In [49]:
arr=d

In [51]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [53]:
arr[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
arr.shape



(1, 3, 5)

In [71]:
arr[0,0,2:-1]

array([2, 3])

In [77]:
arr[0,1,3:5]

array([8, 9])

In [88]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [92]:
d[0,1:3,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [94]:
d[0,1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [98]:
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [102]:
d[0,1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [104]:
arr1=np.arange(120)

In [106]:
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [108]:
arr2=arr1.reshape(3,4,2,5)

In [110]:
arr2

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9]],

        [[ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]]],


       [[[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69]],

        [[ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]]],


       [[[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109]],

        [[110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [114]:
arr2[0]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [128]:
arr1=np.array([[1,2,3],[4,5,6]])

In [130]:
arr2=np.array([[4,5,6],[1,2,3]])

In [136]:
a=np.concatenate((arr1,arr2),axis=0)

In [138]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 2, 3]])